# Escape key is instant
set -s escape-time 0

# increase scrollback buffer size
set -g history-limit 50000

# tmux messages are displayed for 4 seconds
set -g display-time 4000

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# focus events enabled for terminals that support them
set -g focus-events on

# super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

set -g set-titles on
set -g set-titles-string "#T"
set-option -g automatic-rename on

set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',XXX:RGB'

set -g status-fg colour248
set -g status-bg colour236

set -g window-status-format "#[fg=colour248] #I #W "
set -g window-status-current-format "#[fg=colour255,noreverse,bg=colour241] #I #W "

set -g status-right "%a %d %b %I:%M:%S%P"
set -g status-right-length 300

set -g mouse on
set-option -s set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel \
    "xclip -sel c"

bind-key -T root WheelUpPane select-pane -t =\; copy-mode -e\; send-keys -M

set-window-option -g mode-keys vi

# Double LMB Select & Copy (Word)
bind-key -T copy-mode-vi DoubleClick1Pane \
  select-pane \; \
  send-keys -X select-word \; \
  send-keys -X copy-pipe-no-clear "xclip -sel c"

bind-key -n DoubleClick1Pane \
  select-pane \; \
  copy-mode -M \; \
  send-keys -X select-word \; \
  send-keys -X copy-pipe-no-clear "xclip -sel c"

# Triple LMB Select & Copy (Line)
bind-key -T copy-mode-vi TripleClick1Pane \
  select-pane \; \
  send-keys -X select-line \; \
  send-keys -X copy-pipe-no-clear "xclip -sel c"

bind-key -n TripleClick1Pane \
  select-pane \; \
  copy-mode -M \; \
  send-keys -X select-line \; \
  send-keys -X copy-pipe-no-clear "xclip -sel c"

bind-key -T copy-mode-vi Escape send -X clear-selection
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind k kill-session

# Always open using current working directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Navigation between splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key m choose-window "join-pane -s '%%'"

# Reset layout and pane sizes
bind = select-layout tiled

# direnv
set-option -g update-environment "DIRENV_DIFF DIRENV_DIR DIRENV_WATCHES"
set-environment -gu DIRENV_DIFF
set-environment -gu DIRENV_DIR
set-environment -gu DIRENV_WATCHES
set-environment -gu DIRENV_LAYOUT

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
